### ISSUE TITLE
Documentation is confusing

### ISSUE THREAD

**Issue by rglory** [dejanstojanovic/orangepi-pwm#13]
> This project is a proper service library. It is recommended to run it as compiled binary.

How do I compile? How do I install compiled binary and where?

> All configurations are in appsettings.json configuration file.

What directory should I put this file?

>  Once peoject is published

How it is published?

>  . Confiuration values will be automatically reloded once configuration/setting file changes are saved.

Which file and where?

> To run it as a systemd service use the followin service configuration

What should be the file name?

**Comment by dejanstojanovic** [comment]
Hi, I created this project to have a reminder for myself when restoring it on another SBC, so I guess I did not get much into details, but if you are at least a little bit familiar with now .NET Core and systmed works you should be able to run it without any problems. 
Just to give you some heads up with your questions:
- regarding publishing, try to follow some documentation from https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-publish
- any directory would do, I keep mine at /etc/orangepi-fan-service
- answered in first one
- the file snipet is in the readme.md and you need to save it inside /etc/systemd/system directory as also mentioned in the readme.md
- any name you want, I call mine orangepi-fan.service, so the full path is /etc/systemd/system/orangepi-fan.service and content is service unit file snipet

I hope this helps, but try to read a bit of documenttation regarding the .NET core and systemd to make things easier to understand. Anything I can help with, just text me

**Comment by xsetiadi** [comment]
have you able to run this service? im failed. sorry I'm really not understand in dotnet
